### ISSUE TITLE
Simple example is not working

### ISSUE THREAD

**Issue by MiltonCobo** [calebfoss/p5-marker#1]
Hi! I implemented the following example in the READ ME: 

<canvas
  width="400"
  height="400"
  square_angle="0"
  angle_mode="DEGREES"
  canvas_background="20"
  stroke_color="NONE"
>
  <square
    anchor="width / 2, height / 2"
    s="200"
    rect_mode="CENTER"
    fill_color="180, 40, 20"
    angle="square_angle"
    square_angle="square_angle + 1"
  />
  <circle x="width / 2" y="height * 0.75" d="100" fill_color="20, 60, 180" />
</canvas>

and it is diplaying the error below:

core.js:375 Uncaught (in promise) TypeError: Cannot read private member #updateFunctions from an object whose class did not declare it...

The example works without the declaration: square_angle="0" inside the canvas tag.
What is going on?
Thanks very much!

**Comment by calebfoss** [comment]
Hello! Thank you for your interest in this project and for opening the first issue ever!

It looks like a new feature I'm developing is causing this issue, so I've reverted the main branch.

I have that example code running here:  https://editor.p5js.org/p5-marker/sketches/X1_ssnAHw
In the index.html, I needed to update the CDN link to see the changes:
```
<script src="https://cdn.jsdelivr.net/gh/calebfoss/p5-marker@0.1.0-alpha/latest_build/p5.marker.js" defer></script>
```
I've also updated the script tag in the [empty example](https://editor.p5js.org/p5-marker/sketches/NyMiMkbAH).

Please let me know if that works for you and thanks again for bringing this to my attention!

**Comment by MiltonCobo** [comment]
Thanks! I am a math teacher in Brazil, using p5 for my classes. I am sure
your library will be super useful!
Milton.

Em sáb., 14 de jan. de 2023 14:55, Caleb Foss ***@***.***>
escreveu:

**Comment by calebfoss** [comment]
Good to meet you! I teach design classes in Chicago. p5 seems like an awesome tool for math classes.

Sounds like this is resolved, but if you run into that issue again, feel free to re-open the issue.

**Comment by MiltonCobo** [comment]
I forgot to mention that I love your p5VideoRecorder.
